apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: pl-param-x
    value: $(body.head_commit.id)
  - name: pl-param-y
    value: $(body.repository.url)
  - name: pl-param-xy
    value: $(header.Content-Type)