apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: input-x
    value: $(body.input-x)
  - name: input-y
    value: $(body.input-y)
  - name: artifact-name
    value: $(body.artifact-name)
