apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: math-multiply
spec:
  resources:
    inputs:
      - name: flows
        type: git
  steps:
    - name: multiply
      image: python:3.8.5-alpine3.11
      workingDir: /workspace/flows/src
      command: ["python"]
      args: ["multiply.py",  "200", "500"]