apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: math-divide-run-
spec:
  resources:
    inputs:
    - name: flows
      resourceRef:
        name: math-git-resource
  serviceAccountName: ""
  taskRef:
    name: math-divide