apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: math-subtract-params
spec:
  params:
    - name: inputs
      type: array
  resources:
    inputs:
      - name: flows
        type: git
  steps:
    - name: subtract
      image: python:3.8.5-alpine3.11
      workingDir: /workspace/flows/src
      command: ["python"]
      args: ["subtract.py", "$(params.inputs[*])"]