apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: math-sequential-params-run-
spec:
  params:
  - name: pl-param-x
    value: "7"
  - name: pl-param-xy
    value:
    - "12"
    - "7"
  - name: pl-param-y
    value: "11"
  pipelineRef:
    name: math-sequential-params
  resources:
  - name: pipeline-source-repo
    resourceRef:
      name: math-git-resource