apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: math-low-workspace
spec:
  resources:
    inputs:
      - name: flows
        type: git
  workspaces:
  - name: filedrop
  steps:
    - name: low
      image: python:3.8.5-alpine3.11
      workingDir: /workspace/flows/src
      command: ["python"]
      args: ["low.py"]